Repository prebid/prebid-mobile-android, pull requests merged in 2021-04, with the labels that each got.

#253 PrebidServerAdapter errors alternative solution
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/http/HTTPPost.java
  PrebidMobile/src/test/java/org/prebid/mobile/PrebidNativeNativeTest.java
Labels: bug

#242 Support External UserId Solutions in Prebid Mobile SDK
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/MainActivity.java
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/ExternalUserId.java
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerAdapter.java
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/StorageUtils.java
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/TargetingParams.java
  PrebidMobile/src/test/java/org/prebid/mobile/ExternalUIDTest.java
  PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
  PrebidMobile/src/test/java/org/prebid/mobile/TargetingParamsTest.java
Labels: feature, needs_docs

#255 Adapt Prebid SDK to AdManager v20.0.0
  Example/PrebidDemoJava/build.gradle
  Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/AdManagerComplexTest.java
  Example/PrebidDemoJava/src/androidTest/java/org/prebid/mobile/app/ExtraTests.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconBannerGamDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconBannerVideoGamDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconInterstitialGamDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconInterstitialVideoGamDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/RubiconRewardedVideoGamDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrBannerGamDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrInterstitialGamDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrNativeInAppGAMDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrNativeInAppMoPubDemoActivity.java
  Example/PrebidDemoJava/src/main/java/org/prebid/mobile/app/XandrNativeInBannerGamDemoActivity.java
  Example/PrebidDemoKotlin/build.gradle
  Example/PrebidDemoKotlin/src/main/java/org/prebid/mobile/prebidkotlindemo/DemoActivity.kt
  PrebidMobile/PrebidMobile-core/proguard-rules.pro
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/Util.java
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/addendum/AdViewUtils.java
  PrebidMobile/build.gradle
  PrebidMobile/gradle.properties
  PrebidMobile/src/test/java/org/prebid/mobile/DemandFetcherTest.java
  PrebidMobile/src/test/java/org/prebid/mobile/PrebidServerAdapterTest.java
  PrebidMobile/src/test/java/org/prebid/mobile/ResultCodeTest.java
  PrebidMobile/src/test/java/org/prebid/mobile/UtilTest.java
  build.gradle
Labels: enhancement

#258 Release 1.11
  Example/PrebidDemoJava/build.gradle
  PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidServerSettings.java
  PrebidMobile/publisher.gradle
  README.md
  build.gradle
  scripts/Maven/PrebidMobile-core-pom.xml
  scripts/Maven/PrebidMobile-pom.xml
Labels: release
